version: "3.8"

services:
  mysql8:
    image: mysql:8.1.0
    env_file:
      - ./mysql/8/.env
    volumes:
      - mysql8_data:/var/lib/mysql
      - ./mysql/8/conf:/etc/mysql/conf.d
      - ./mysql/8/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  #  postgres:
  #    image: "postgres:12.2"
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    env_file:
  #      - ./postgres/.env
  #    ports:
  #      - "5432"
  #    networks:
  #      - "network1"

  elasticsearch:
    image: "elasticsearch:7.17.7"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    env_file:
      - ./elasticsearch/.env
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cat/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  redis:
    image: "redis:7.2.1"
    ports:
      - "6379:6379"

  #  minio:
  #    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
  #    volumes:
  #      - minio_data:/data
  #    environment:
  #      MINIO_ROOT_USER: minio
  #      MINIO_ROOT_PASSWORD: minio
  #    command: server --address :9000 --console-address :9001 --compat /data
  #    ports:
  #      - "9000"
  #      - "9001"

  nacos:
    image: nacos/nacos-server:v2.2.3
    env_file:
      - ./nacos/.env
    #    volumes:
    #      - ./nacos/custom.properties:/home/nacos/init.d/
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql8:
        condition: service_healthy

volumes:
  mysql8_data: { }
  elasticsearch_data: { }
  # postgres_data: {}
  # minio_data: {}

#networks:
#  network1: {}